project_id = "gerwikyaggikykftcyxm"

[functions.visual-search]
verify_jwt = true

[functions.catalog-ingest]
verify_jwt = true

[functions.catalog-scraper]
verify_jwt = true

[functions.pinterest-extract]
verify_jwt = false

[functions.inspiration-feed]
verify_jwt = false

[functions.ebay-account-deletion]
verify_jwt = false
